# Values for ElasticSearch charts
# https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml

persistence:
  enabled: false


resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

initResources:
  limits:
    cpu: "25m"
    # memory: "128Mi"
  requests:
    cpu: "25m"
    memory: "128Mi"