## ----
## Values for Confluent Platform (Kafka and friends)
## ----

brokers: 2

cp-zookeeper:
  imageTag: 5.4.2
  # servers: 1
  persistence:
    enabled: false

cp-kafka:
  imageTag: 5.4.2
  # brokers: 1
  persistence:
    enabled: false

cp-control-center:
  imageTag: 5.4.1
  enabled: true
#  resources:
#    limits:
#      cpu: 100m
#      memory: 128Mi
#  configurationOverrides:
#    "replication.factor": 1

cp-kafka-connect:
  imageTag: 5.4.2

#  configurationOverrides:
#    "config.storage.replication.factor": 1
#    "offset.storage.replication.factor": 1
#    "status.storage.replication.factor": 1


# configurationOverrides:
#   "default.replication.factor": 1
#   "min.insync.replicas": 1
#   "offsets.topic.replication.factor": 1
#   "transaction.state.log.min.isr": 1
#   "transaction.state.log.num.partitions": 1
#   "transaction.state.log.replication.factor": 1
#   "transaction.state.replication.factor": 1
#   "auto.create.topics.enable": true