apiVersion: v1
kind: ConfigMap
metadata:
  name: rsvp-feeder-config
  namespace: hello-k8
data:
  SCHEMA_REGISTRY_URL: http://one-cp-schema-registry:8081
  BOOTSTRAP_SERVERS: one-cp-kafka:9092
  KAMON_AMP_API_KEY: av2ap94b6uicb2ccifnurbc405
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-feeder
  labels:
    app: rsvp-feeder-app
    version: v4
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rsvp-feeder-app
  template:
    metadata:
      labels:
        app: rsvp-feeder-app
    spec:
      containers:
        - name: rsvp-feeder
          image: pinkstack/rsvp-feeder:e80d18
          envFrom:
            - configMapRef:
                name: rsvp-feeder-config